##Q1

In [19]:
import numpy as np

In [20]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[4, 5, 6],
              [7, 8, 9]])

v_stacked = np.vstack([A, B])
h_stacked = np.hstack([A, B])

print("A:\n", A)
print("B:\n", B)
print("Vertical stack (vstack):\n", v_stacked)
print("Horizontal stack (hstack):\n", h_stacked)

A:
 [[1 2 3]
 [4 5 6]]
B:
 [[4 5 6]
 [7 8 9]]
Vertical stack (vstack):
 [[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
Horizontal stack (hstack):
 [[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [21]:
common = np.intersect1d(A.ravel(), B.ravel())
print("Common elements between A and B:", common)

Common elements between A and B: [4 5 6]


In [22]:
low, high = 5, 10
in_range_mask = (A >= low) & (A <= high)
in_range_vals = A[in_range_mask]
print(f"Values in A between {low} and {high} (inclusive):", in_range_vals)

Values in A between 5 and 10 (inclusive): [5 6]


In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered = iris_2d[mask]

print("Filtered iris_2d shape:", filtered.shape)
print("Filtered rows:\n", filtered)

Filtered iris_2d shape: (6, 4)
Filtered rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


##Q2

In [24]:
import pandas as pd

In [25]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

result = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print("Every 20th row (columns: Manufacturer, Model, Type):")
print(result)


Every 20th row (columns: Manufacturer, Model, Type):
   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print("\nMissing values replaced with column means:")
print(df[['Min.Price', 'Max.Price']].head())


Missing values replaced with column means:
   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


/tmp/ipython-input-708459314.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
/tmp/ipython-input-708459314.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True

In [27]:
df2 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print("\nOriginal random DataFrame:")
print(df2.head())

rows_over_100 = df2[df2.sum(axis=1) > 100]
print("\nRows with sum > 100:")
print(rows_over_100)


Original random DataFrame:
    0   1   2   3
0  35  28  29  37
1  13  32  18  10
2  23  11  22  15
3  18  29  13  37
4  24  21  15  19

Rows with sum > 100:
     0   1   2   3
0   35  28  29  37
5   27  23  18  35
10  16  20  36  37
12  15  10  39  38
14  37  39  36  35
